### ISSUE TITLE
Typing test can be finished with incorrect characters

### ISSUE THREAD

**Issue by happyRip** [maaslalani/typer#12]
`typer` should check if all characters that were captured are valid, before finishing the test. Characters highlighted red are not counted towards WPM score, but don't block from test finishing.
![typer](https://user-images.githubusercontent.com/73070465/139712729-80db1780-0858-4fc5-ad83-96c0d7de26c8.png)

**Comment by maaslalani** [comment]
I may be misunderstanding but I think instead of blocking the test from finishing, we could emulate how https://www.keybr.com/ works and block progressing to the next letter until it is correctly typed. This will ensure all characters are correctly typed but not make the user need to backspace all the way back in the event that they mistyped a character near the beginning.

**Comment by happyRip** [comment]
I was inspired by https://www.monkeytype.com/ implementation. I could add an option to input text longer than the text or implement it like in https://www.keybr.com/

**Comment by maaslalani** [comment]
> I was inspired by https://www.monkeytype.com/ implementation. I could add an option to input text longer than the text or implement it like in https://www.keybr.com/

👍 Let me test this implementation out first and see if I find it good, thank you for this work btw ❤️

**Comment by maaslalani** [comment]
https://github.com/maaslalani/typer/pull/14#issuecomment-961606918
